# Generated by Django 5.2.8 on 2026-01-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TargetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.workitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.workitem')),
            ],
        ),
    ]
