# Generated by Django 5.2.8 on 2026-01-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetprogress',
            name='report',
        ),
        migrations.RemoveField(
            model_name='targetprogress',
            name='work_item',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProgressEntry',
        ),
        migrations.DeleteModel(
            name='TargetProgress',
        ),
        migrations.DeleteModel(
            name='WorkCategory',
        ),
        migrations.DeleteModel(
            name='WorkItem',
        ),
    ]
