# Generated by Django 5.2.8 on 2026-01-06 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(choices=[('OSHA', 'OSHA'), ('CRB', 'CRB'), ('NEMC', 'NEMC'), ('AQRB', 'AQRB')], max_length=20)),
                ('registration_no', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Expired', 'Expired'), ('Pending', 'Pending')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['expiry_date'],
                'permissions': [('can_approve_compliance', 'Can approve compliance')],
            },
        ),
    ]
