# Generated by Django 5.2.8 on 2026-01-07 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('setup', '0003_authority_delete_constructionstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliances', to='setup.authority'),
        ),
    ]
