# Generated by Django 5.2.8 on 2026-01-06 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contract_sum', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contract_duration_months', models.PositiveIntegerField()),
                ('contract_signing_date', models.DateField()),
                ('site_possession_date', models.DateField()),
                ('mobilization_start', models.DateField()),
                ('mobilization_end', models.DateField()),
                ('commencement_date', models.DateField()),
                ('practical_completion_date', models.DateField()),
                ('delay_status', models.CharField(default='Nil', max_length=100)),
                ('defects_liability_period_days', models.PositiveIntegerField(default=365)),
                ('defects_start', models.DateField(blank=True, null=True)),
                ('defects_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='setup.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('access_projects', 'Can access projects')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'contractor')},
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.project')),
                ('project_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.projectrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
