# Generated by Django 5.2.8 on 2026-01-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipant',
            options={'ordering': ['project_role']},
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together=set(),
        ),
    ]
