# Generated by Django 5.2.8 on 2026-01-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payee', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'permissions': [('access_finance', 'Can access financial data')],
            },
        ),
        migrations.CreateModel(
            name='PaymentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=100)),
                ('certified_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'permissions': [('access_finance', 'Can access financial data')],
            },
        ),
    ]
