# Generated by Django 5.2.8 on 2026-01-07 01:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundtransaction',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='paymentcertificate',
            options={'ordering': ['-payment_date']},
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='paymentcertificate',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='paymentcertificate',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='pv_or_receipt_no',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='credit', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='amount_from',
            field=models.CharField(default='mimi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='amount_to',
            field=models.CharField(default='mmd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='certificate_no',
            field=models.CharField(default=333, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='date_certified',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='pv_no',
            field=models.CharField(default=222, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundtransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='paymentcertificate',
            name='certified_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentcertificate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_certificates', to='projects.project'),
        ),
    ]
