# Generated by Django 5.2.8 on 2026-01-06 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('tin_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('access_setup', 'Can access setup module'), ('access_clients', 'Can access client module'), ('create_clients', 'Can create clients'), ('edit_clients', 'Can edit clients'), ('delete_clients', 'Can delete clients')],
            },
        ),
        migrations.CreateModel(
            name='ContractorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_contractor_types', 'Can view contractor types'), ('create_contractor_types', 'Can create contractor types'), ('edit_contractor_types', 'Can edit contractor types'), ('delete_contractor_types', 'Can delete contractor types')],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('tin_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('contractor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.contractortype')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_contractors', 'Can view contractors'), ('create_contractors', 'Can create contractors'), ('edit_contractors', 'Can edit contractors'), ('delete_contractors', 'Can delete contractors')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_project_roles', 'Can view project roles'), ('create_project_roles', 'Can create project roles'), ('edit_project_roles', 'Can edit project roles'), ('delete_project_roles', 'Can delete project roles')],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Category',
                'verbose_name_plural': 'Work Categories',
                'ordering': ['name'],
                'permissions': [('view_work_categories', 'Can view work categories'), ('create_work_categories', 'Can create work categories'), ('edit_work_categories', 'Can edit work categories'), ('delete_work_categories', 'Can delete work categories')],
            },
        ),
    ]
