# Generated by Django 5.2.8 on 2026-01-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_authority_delete_constructionstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='contractortype',
            options={'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='projectrole',
            options={'ordering': ['name'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'ordering': ['name'], 'permissions': [], 'verbose_name': 'Work Category', 'verbose_name_plural': 'Work Categories'},
        ),
    ]
