# Generated by Django 5.2.8 on 2026-01-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_client_options_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
