# Generated by Django 5.2.8 on 2026-01-09 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_projectrole_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='authority',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_authority_name'),
        ),
        migrations.AddConstraint(
            model_name='workcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_work_category_name'),
        ),
    ]
