# Generated by Django 5.2.8 on 2026-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard', 'Can view dashboard')],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
