# Generated by Django 5.2.8 on 2026-01-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dashboardaccess_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardaccess',
            options={'permissions': [], 'verbose_name': 'Dashboard Access', 'verbose_name_plural': 'Dashboard Access'},
        ),
    ]
