# Generated by Django 5.2.8 on 2026-01-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dashboardaccess_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardAccess',
            new_name='Dashboard',
        ),
    ]
