# Generated by Django 5.2.8 on 2026-01-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_dashboardaccess_dashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
    ]
