# Generated by Django 5.2.8 on 2026-01-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'permissions': [('access_reports', 'Can access reports'), ('approve_report', 'Can approve report')]},
        ),
    ]
