# Generated by Django 5.2.8 on 2026-01-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_targetprogress_report_and_more'),
        ('projects', '0002_alter_projectparticipant_options_and_more'),
        ('reports', '0002_alter_monthlyreport_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('progress', 'Progress Report'), ('finance', 'Finance Report'), ('resource', 'Resource Utilization'), ('quality', 'Quality Summary')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField()),
                ('file', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reportdefinition')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
