# Generated by Django 5.2.8 on 2026-01-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportdefinition_reportrun_delete_monthlyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdefinition',
            options={'permissions': [('view_reports', 'Can view reports'), ('generate_reports', 'Can generate reports'), ('download_reports', 'Can download reports')]},
        ),
    ]
