# Generated by Django 5.2.8 on 2026-01-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportdefinition_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrun',
            name='report_definition',
        ),
        migrations.RemoveField(
            model_name='reportrun',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='reportrun',
            name='project',
        ),
        migrations.DeleteModel(
            name='ReportDefinition',
        ),
        migrations.DeleteModel(
            name='ReportRun',
        ),
    ]
