# Generated by Django 5.2.8 on 2026-01-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financereport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectreport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='qualityreport',
            options={'managed': False},
        ),
    ]
