# Generated by Django 5.2.8 on 2026-01-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_resourcesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
