# Generated by Django 5.2.8 on 2026-01-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectparticipant_options_and_more'),
        ('reports', '0009_progressreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.PositiveIntegerField()),
                ('report_title', models.CharField(max_length=255)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='report_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
