# Generated by Django 5.2.8 on 2026-01-08 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtest',
            options={'ordering': ['-test_date'], 'permissions': [('can_approve_material', 'Can approve material test')]},
        ),
        migrations.AlterModelOptions(
            name='workapproval',
            options={'ordering': ['-approval_date'], 'permissions': [('can_approve_work', 'Can approve work')]},
        ),
        migrations.AlterField(
            model_name='materialtest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
