# Generated by Django 5.2.8 on 2026-01-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_alter_materialtest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialtest',
            old_name='lab_name',
            new_name='consultant',
        ),
    ]
