# Generated by Django 5.2.8 on 2026-01-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manpower',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='manpower',
            old_name='report_month',
            new_name='start_date',
        ),
    ]
