# Generated by Django 5.2.8 on 2026-01-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectparticipant_options_and_more'),
        ('resources', '0002_alter_manpower_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpower',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manpower', to='projects.project'),
            preserve_default=False,
        ),
    ]
