# Generated by Django 5.2.8 on 2026-01-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_manpower_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'permissions': []},
        ),
    ]
