# Generated by Django 5.2.8 on 2026-01-08 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='site_visitors/')),
                ('visit_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Visitor',
                'verbose_name_plural': 'Site Visitors',
                'ordering': ['-visit_date'],
                'permissions': [('view_site_visitor', 'Can view site visitors'), ('add_site_visitor', 'Can add site visitors'), ('change_site_visitor', 'Can edit site visitors'), ('delete_site_visitor', 'Can delete site visitors')],
            },
        ),
    ]
