# Generated by Django 5.2.8 on 2026-01-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0002_sitevisitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemanage',
            options={'permissions': [('access_sitemanage', 'Can access site management module')]},
        ),
    ]
