# Generated by Django 5.2.8 on 2026-01-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0003_alter_sitemanage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisitor',
            options={'ordering': ['-visit_date'], 'verbose_name': 'Site Visitor', 'verbose_name_plural': 'Site Visitors'},
        ),
        migrations.RemoveConstraint(
            model_name='activity',
            name='activity_planned_date_valid',
        ),
    ]
