# Generated by Django 5.2.8 on 2026-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0004_alter_sitevisitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
