# Generated by Django 5.2.8 on 2026-01-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectparticipant_options_and_more'),
        ('sitemanage', '0005_progresslog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_visitors', to='projects.project'),
            preserve_default=False,
        ),
    ]
