# Generated by Django 5.2.8 on 2026-01-10 02:07

import django.db.models.deletion
import sitemanage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectparticipant_options_and_more'),
        ('sitemanage', '0006_sitevisitor_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sitemanage.models.project_image_upload_path)),
                ('image_date', models.DateField()),
                ('figure_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Site Project Image',
                'verbose_name_plural': 'Site Project Images',
                'ordering': ['-image_date', '-created_at'],
            },
        ),
    ]
