# Generated by Django 5.2.8 on 2026-01-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0007_siteprojectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemanage',
            options={'permissions': [('access_sitemanage', 'Can access site management')]},
        ),
    ]
