# Generated by Django 5.2.8 on 2026-01-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectparticipant_options_and_more'),
        ('sitemanage', '0008_alter_sitemanage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprojectimage',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_images', to='sitemanage.activity'),
        ),
        migrations.AlterField(
            model_name='siteprojectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project'),
        ),
    ]
