# Generated by Django 5.2.8 on 2026-01-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0009_siteprojectimage_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprojectimage',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_images', to='sitemanage.activity'),
            preserve_default=False,
        ),
    ]
