# Generated by Django 5.2.8 on 2026-01-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0010_alter_siteprojectimage_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemanage',
            options={'managed': False, 'permissions': [('access_sitemanage', 'Can access site management')]},
        ),
    ]
